REM   Script: Exerc. 2
REM   2. Listar professores e suas especialidades em ordem decrescente
Faça uma consulta que exiba o nome dos professores e suas especialidades, ordenando os professores em ordem alfabética inversa (decrescente).

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE professores CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE professores ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    especialidade VARCHAR2(100) NOT NULL 
);

INSERT INTO professores (nome, especialidade) VALUES ('Ana Oliveira', 'Matemática');

INSERT INTO professores (nome, especialidade) VALUES ('Carlos Silva', 'Física');

INSERT INTO professores (nome, especialidade) VALUES ('Beatriz Santos', 'História');

INSERT INTO professores (nome, especialidade) VALUES ('Daniel Lima', 'Química');

INSERT INTO professores (nome, especialidade) VALUES ('Eduardo Pereira', 'Biologia');

SELECT nome, especialidade 
FROM professores 
ORDER BY nome DESC;

