REM   Script: Exerc. 9
REM   9. Contar o número total de turmas e listar por professor
Crie uma consulta que exiba o nome dos professores e o número total de turmas que cada professor leciona, ordenando pelos professores com mais turmas.

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE professores CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE professores ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    especialidade VARCHAR2(100) NOT NULL 
);

INSERT INTO professores (nome, especialidade) VALUES ('Ana Oliveira', 'Matemática');

INSERT INTO professores (nome, especialidade) VALUES ('Carlos Silva', 'Física');

INSERT INTO professores (nome, especialidade) VALUES ('Beatriz Santos', 'História');

INSERT INTO professores (nome, especialidade) VALUES ('Daniel Lima', 'Química');

INSERT INTO professores (nome, especialidade) VALUES ('Eduardo Pereira', 'Biologia');

SELECT nome, especialidade 
FROM professores 
ORDER BY nome DESC;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE professores CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE professores ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    especialidade VARCHAR2(100) NOT NULL 
);

INSERT INTO professores (nome, especialidade) VALUES ('Ana Oliveira', 'Matemática');

INSERT INTO professores (nome, especialidade) VALUES ('Carlos Silva', 'Física');

INSERT INTO professores (nome, especialidade) VALUES ('Beatriz Santos', 'História');

INSERT INTO professores (nome, especialidade) VALUES ('Daniel Lima', 'Química');

INSERT INTO professores (nome, especialidade) VALUES ('Eduardo Pereira', 'Biologia');

SELECT nome, especialidade 
FROM professores 
ORDER BY nome DESC;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Biologia', 50);

SELECT nome, carga_horaria 
FROM disciplinas 
ORDER BY carga_horaria DESC;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE alunos CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE alunos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    status_matricula VARCHAR2(20) NOT NULL 
);

INSERT INTO alunos (nome, status_matricula) VALUES ('João Silva', 'Ativo');

INSERT INTO alunos (nome, status_matricula) VALUES ('Maria Santos', 'Concluído');

INSERT INTO alunos (nome, status_matricula) VALUES ('Pedro Oliveira', 'Ativo');

INSERT INTO alunos (nome, status_matricula) VALUES ('Ana Costa', 'Trancado');

INSERT INTO alunos (nome, status_matricula) VALUES ('Lucas Lima', 'Ativo');

INSERT INTO alunos (nome, status_matricula) VALUES ('Laura Mendes', 'Concluído');

INSERT INTO alunos (nome, status_matricula) VALUES ('Carla Souza', 'Trancado');

INSERT INTO alunos (nome, status_matricula) VALUES ('Rafael Ferreira', 'Ativo');

SELECT status_matricula, COUNT(*) AS numero_alunos 
FROM alunos 
GROUP BY status_matricula;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Ciências Exatas');

INSERT INTO cursos (nome) VALUES ('Humanidades');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Sociologia', 50);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1); -- Matemática em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2); -- Física em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 4); -- Química em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3); -- História em Humanidades 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 5); -- Sociologia em Humanidades 
 
-- 8. Consulta para listar cursos com a soma total da carga horária de suas disciplinas 
SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Ciências Exatas');

INSERT INTO cursos (nome) VALUES ('Humanidades');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Sociologia', 50);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1); -- Matemática em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2); -- Física em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 4); -- Química em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3); -- História em Humanidades 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 5); -- Sociologia em Humanidades 
 
-- 8. Consulta para listar cursos com a soma total da carga horária de suas disciplinas 
SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Ciências Exatas');

INSERT INTO cursos (nome) VALUES ('Humanidades');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Sociologia', 50);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1); -- Matemática em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2); -- Física em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 4); -- Química em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3); -- História em Humanidades 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 5); -- Sociologia em Humanidades 
 
-- 8. Consulta para listar cursos com a soma total da carga horária de suas disciplinas 
SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Ciências Exatas');

INSERT INTO cursos (nome) VALUES ('Humanidades');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Sociologia', 50);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1); -- Matemática em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2); -- Física em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 4); -- Química em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3); -- História em Humanidades 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 5); -- Sociologia em Humanidades 
 
-- 8. Consulta para listar cursos com a soma total da carga horária de suas disciplinas 
SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Ciências Exatas');

INSERT INTO cursos (nome) VALUES ('Humanidades');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Sociologia', 50);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1); -- Matemática em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2); -- Física em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 4); -- Química em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3); -- História em Humanidades 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 5); -- Sociologia em Humanidades 
 
-- 8. Consulta para listar cursos com a soma total da carga horária de suas disciplinas 
SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Ciências Exatas');

INSERT INTO cursos (nome) VALUES ('Humanidades');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Sociologia', 50);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1); -- Matemática em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2); -- Física em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 4); -- Química em Ciências Exatas 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3); -- História em Humanidades 
INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 5); -- Sociologia em Humanidades 
 
-- 8. Consulta para listar cursos com a soma total da carga horária de suas disciplinas 
SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Ciências Exatas');

INSERT INTO cursos (nome) VALUES ('Humanidades');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Matemática', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 60);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('História', 40);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Química', 70);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Sociologia', 50);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 4);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 5);

SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE professores_turmas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE professores CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE turmas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE professores ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE turmas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE professores_turmas ( 
    professor_id NUMBER NOT NULL, 
    turma_id NUMBER NOT NULL, 
    FOREIGN KEY (professor_id) REFERENCES professores(id), 
    FOREIGN KEY (turma_id) REFERENCES turmas(id) 
);

INSERT INTO professores (nome) VALUES ('Ana Oliveira');

INSERT INTO professores (nome) VALUES ('Carlos Silva');

INSERT INTO professores (nome) VALUES ('Beatriz Santos');

INSERT INTO professores (nome) VALUES ('Daniel Lima');

INSERT INTO professores (nome) VALUES ('Eduardo Pereira');

INSERT INTO turmas (nome) VALUES ('Turma A');

INSERT INTO turmas (nome) VALUES ('Turma B');

INSERT INTO turmas (nome) VALUES ('Turma C');

INSERT INTO turmas (nome) VALUES ('Turma D');

INSERT INTO turmas (nome) VALUES ('Turma E');

INSERT INTO turmas (nome) VALUES ('Turma F');

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 1);

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE professores_turmas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE professores CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE turmas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE professores ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE turmas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 4);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (3, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 4);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 5);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 2);

SELECT p.nome 
FROM professores p 
JOIN professores_turmas pt ON p.id = pt.professor_id 
GROUP BY p.nome 
HAVING COUNT(pt.turma_id) > 3;

CREATE TABLE professores_turmas ( 
    professor_id NUMBER NOT NULL, 
    turma_id NUMBER NOT NULL, 
    FOREIGN KEY (professor_id) REFERENCES professores(id), 
    FOREIGN KEY (turma_id) REFERENCES turmas(id) 
);

INSERT INTO professores (nome) VALUES ('Ana Oliveira');

INSERT INTO professores (nome) VALUES ('Carlos Silva');

INSERT INTO professores (nome) VALUES ('Beatriz Santos');

INSERT INTO professores (nome) VALUES ('Daniel Lima');

INSERT INTO professores (nome) VALUES ('Eduardo Pereira');

INSERT INTO turmas (nome) VALUES ('Turma A');

INSERT INTO turmas (nome) VALUES ('Turma B');

INSERT INTO turmas (nome) VALUES ('Turma C');

INSERT INTO turmas (nome) VALUES ('Turma D');

INSERT INTO turmas (nome) VALUES ('Turma E');

INSERT INTO turmas (nome) VALUES ('Turma F');

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 4);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (3, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 4);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 5);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 2);

SELECT p.nome 
FROM professores p 
JOIN professores_turmas pt ON p.id = pt.professor_id 
GROUP BY p.nome 
HAVING COUNT(pt.turma_id) > 3;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE alunos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE alunos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE alunos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE alunos_disciplinas ( 
    aluno_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (aluno_id) REFERENCES alunos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO alunos (nome) VALUES ('João Silva');

INSERT INTO alunos (nome) VALUES ('Maria Santos');

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE alunos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE alunos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE alunos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE alunos_disciplinas ( 
    aluno_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (aluno_id) REFERENCES alunos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO alunos (nome) VALUES ('João Silva');

INSERT INTO alunos (nome) VALUES ('Maria Santos');

INSERT INTO alunos (nome) VALUES ('Pedro Oliveira');

INSERT INTO alunos (nome) VALUES ('Ana Costa');

INSERT INTO alunos (nome) VALUES ('Lucas Lima');

INSERT INTO disciplinas (nome) VALUES ('Matemática');

INSERT INTO alunos (nome) VALUES ('Pedro Oliveira');

INSERT INTO alunos (nome) VALUES ('Ana Costa');

INSERT INTO alunos (nome) VALUES ('Lucas Lima');

INSERT INTO disciplinas (nome) VALUES ('Matemática');

INSERT INTO disciplinas (nome) VALUES ('Física');

INSERT INTO disciplinas (nome) VALUES ('História');

INSERT INTO disciplinas (nome) VALUES ('Química');

INSERT INTO disciplinas (nome) VALUES ('Biologia');

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (1, 1);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (1, 2);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (2, 2);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (2, 3);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (2, 4);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (3, 1);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (3, 3);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (4, 1);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (4, 4);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (4, 5);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (5, 2);

SELECT a.nome, COUNT(ad.disciplina_id) AS numero_disciplinas 
FROM alunos a 
JOIN alunos_disciplinas ad ON a.id = ad.aluno_id 
GROUP BY a.nome 
HAVING COUNT(ad.disciplina_id) > 1 
ORDER BY numero_disciplinas DESC;

INSERT INTO disciplinas (nome) VALUES ('Física');

INSERT INTO disciplinas (nome) VALUES ('História');

INSERT INTO disciplinas (nome) VALUES ('Química');

INSERT INTO disciplinas (nome) VALUES ('Biologia');

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (1, 1);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (1, 2);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (2, 2);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (2, 3);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (2, 4);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (3, 1);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (3, 3);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (4, 1);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (4, 4);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (4, 5);

INSERT INTO alunos_disciplinas (aluno_id, disciplina_id) VALUES (5, 2);

SELECT a.nome, COUNT(ad.disciplina_id) AS numero_disciplinas 
FROM alunos a 
JOIN alunos_disciplinas ad ON a.id = ad.aluno_id 
GROUP BY a.nome 
HAVING COUNT(ad.disciplina_id) > 1 
ORDER BY numero_disciplinas DESC;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Engenharia');

INSERT INTO cursos (nome) VALUES ('Medicina');

INSERT INTO cursos (nome) VALUES ('Direito');

INSERT INTO cursos (nome) VALUES ('Ciências da Computação');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Cálculo', 500);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 400);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Histologia', 600);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Anatomia', 700);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Programação', 300);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Algoritmos', 350);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Constitucional', 450);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Penal', 400);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 4);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 7);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 8);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 5);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 6);

SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome 
HAVING SUM(d.carga_horaria) > 2000;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Engenharia');

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Engenharia');

INSERT INTO cursos (nome) VALUES ('Medicina');

INSERT INTO cursos (nome) VALUES ('Direito');

INSERT INTO cursos (nome) VALUES ('Ciências da Computação');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Cálculo', 800);   -- Aumentando carga horária 
INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 700);    -- Aumentando carga horária 
INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Histologia', 600);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Anatomia', 700);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Programação', 300);

INSERT INTO cursos (nome) VALUES ('Medicina');

INSERT INTO cursos (nome) VALUES ('Direito');

INSERT INTO cursos (nome) VALUES ('Ciências da Computação');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Cálculo', 500);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 400);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Histologia', 600);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Anatomia', 700);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Programação', 300);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Algoritmos', 350);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Constitucional', 450);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Penal', 400);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 4);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 7);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 8);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 5);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 6);

SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome 
HAVING SUM(d.carga_horaria) > 2000;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Engenharia');

INSERT INTO cursos (nome) VALUES ('Medicina');

INSERT INTO cursos (nome) VALUES ('Direito');

INSERT INTO cursos (nome) VALUES ('Ciências da Computação');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Cálculo', 800);   -- Aumentando carga horária 
INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 700);    -- Aumentando carga horária 
INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Histologia', 600);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Anatomia', 700);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Programação', 300);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Algoritmos', 350);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Constitucional', 450);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Penal', 400);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 4);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 7);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 8);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 5);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 6);

SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome 
HAVING SUM(d.carga_horaria) > 2000;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Engenharia');

INSERT INTO cursos (nome) VALUES ('Medicina');

INSERT INTO cursos (nome) VALUES ('Direito');

INSERT INTO cursos (nome) VALUES ('Ciências da Computação');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Cálculo', 800);   -- Aumentando carga horária 
INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 700);    -- Aumentando carga horária 
INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Histologia', 600);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Anatomia', 700);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Programação', 300);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Algoritmos', 350);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Constitucional', 450);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Penal', 400);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 4);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 7);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 8);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 5);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 6);

SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome 
HAVING SUM(d.carga_horaria) > 2000;

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Algoritmos', 350);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Constitucional', 450);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Penal', 400);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 4);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 7);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 8);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 5);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 6);

SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome 
HAVING SUM(d.carga_horaria) > 2000;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE cursos_disciplinas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE cursos CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE disciplinas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE cursos ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE disciplinas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL, 
    carga_horaria NUMBER NOT NULL 
);

CREATE TABLE cursos_disciplinas ( 
    curso_id NUMBER NOT NULL, 
    disciplina_id NUMBER NOT NULL, 
    FOREIGN KEY (curso_id) REFERENCES cursos(id), 
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) 
);

INSERT INTO cursos (nome) VALUES ('Engenharia');

INSERT INTO cursos (nome) VALUES ('Medicina');

INSERT INTO cursos (nome) VALUES ('Direito');

INSERT INTO cursos (nome) VALUES ('Ciências da Computação');

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Cálculo', 800);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Física', 700);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Histologia', 600);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Anatomia', 700);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Programação', 300);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Algoritmos', 350);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Constitucional', 450);

INSERT INTO disciplinas (nome, carga_horaria) VALUES ('Direito Penal', 400);

SELECT * FROM cursos;

SELECT * FROM disciplinas;

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 1);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (1, 2);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 3);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (2, 4);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 7);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (3, 8);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 5);

INSERT INTO cursos_disciplinas (curso_id, disciplina_id) VALUES (4, 6);

SELECT c.nome AS curso, SUM(d.carga_horaria) AS carga_horaria_total 
FROM cursos c 
JOIN cursos_disciplinas cd ON c.id = cd.curso_id 
JOIN disciplinas d ON cd.disciplina_id = d.id 
GROUP BY c.nome 
HAVING SUM(d.carga_horaria) > 2000;

BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE professores_turmas CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE professores CASCADE CONSTRAINTS'; 
  EXECUTE IMMEDIATE 'DROP TABLE turmas CASCADE CONSTRAINTS'; 
EXCEPTION 
  WHEN OTHERS THEN 
    IF SQLCODE != -942 THEN 
      RAISE; 
    END IF; 
END; 
/

CREATE TABLE professores ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE turmas ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL 
);

CREATE TABLE professores_turmas ( 
    professor_id NUMBER NOT NULL, 
    turma_id NUMBER NOT NULL, 
    FOREIGN KEY (professor_id) REFERENCES professores(id), 
    FOREIGN KEY (turma_id) REFERENCES turmas(id) 
);

INSERT INTO professores (nome) VALUES ('Ana Oliveira');

INSERT INTO professores (nome) VALUES ('Carlos Silva');

INSERT INTO professores (nome) VALUES ('Beatriz Santos');

INSERT INTO professores (nome) VALUES ('Daniel Lima');

INSERT INTO professores (nome) VALUES ('Eduardo Pereira');

INSERT INTO turmas (nome) VALUES ('Turma A');

INSERT INTO turmas (nome) VALUES ('Turma B');

INSERT INTO turmas (nome) VALUES ('Turma C');

INSERT INTO turmas (nome) VALUES ('Turma D');

INSERT INTO turmas (nome) VALUES ('Turma E');

INSERT INTO turmas (nome) VALUES ('Turma F');

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (1, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (2, 4);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (3, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (3, 5);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 1);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 2);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (4, 6);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 3);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 4);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 5);

INSERT INTO professores_turmas (professor_id, turma_id) VALUES (5, 6);

SELECT p.nome AS professor, COUNT(pt.turma_id) AS total_turmas 
FROM professores p 
JOIN professores_turmas pt ON p.id = pt.professor_id 
GROUP BY p.nome 
ORDER BY total_turmas DESC;

